fileGroups:
  sources:
    - '*.yml'
    - '*.yaml'
    - '*.json'
    - '*.jsonc'
    - '*.toml'
    - '*.lock'

tasks:
  lint:
    command: 'biome check --write-changes'
    inputs:
      - '@globs(sources)'
